# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
