# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170124_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('country_text', models.TextField(default='')),
                ('country_image', models.ImageField(blank=True, height_field='country_image_height_field', null=True, upload_to='', width_field='country_image_width_field')),
                ('country_image_width_field', models.IntegerField(default=0)),
                ('country_image_height_field', models.IntegerField(default=0)),
                ('country_icon', models.ImageField(blank=True, height_field='country_icon_height_field', null=True, upload_to='', width_field='country_icon_width_field')),
                ('country_icon_width_field', models.IntegerField(default=0)),
                ('country_icon_height_field', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
