# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_distance_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='style',
            name='info',
            field=models.TextField(default='Info about'),
        ),
    ]
