# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170124_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('male', models.BooleanField(default=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Country')),
            ],
            options={
                'db_table': 'swimmers',
            },
        ),
    ]
