# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='swimmer_image',
            field=models.ImageField(blank=True, height_field='swimmer_image_height_field', null=True, upload_to='', width_field='swimmer_image_width_field'),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='swimmer_image_height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='swimmer_image_width_field',
            field=models.IntegerField(default=0),
        ),
    ]
